imports:
    - { resource: '@PrestaCMSThemeBasicBundle/Resources/config/theme/creative.yml' }

parameters:
    presta_cms.page.factory.class: Application\Presta\CMSCoreBundle\Factory\PageFactory

sonata_admin:
  dashboard:
      blocks:
          - { position: right, type: presta_cms.block.dashboard.cms }

presta_cms_core:
    default_website: /website/sandbox
    default_locale: en
    websites:
        prestacms-sandbox:
            path: /website/sandbox
            hosts:
                dev:
                    en:
                        locale: en
                        host: prestacms-sandbox
                    fr:
                        locale: fr
                        host: prestacms-sandbox.fr
                prod:
                    en:
                        locale: en
                        host: prestacms-sandbox
                    fr:
                        locale: fr
                        host:  prestacms-sandbox.fr
    blocks:
        global:
            excluded:
                - presta_cms.block.ajax
        left:
            excluded:
                - presta_cms.block.media_advanced
        presta_cms.block.container:
            excluded:
                - presta_cms.block.page_children
