imports:
#    - { resource: '@PrestaCMSThemeBasicBundle/Resources/config/config.yml' }
    - { resource: '@PrestaCMSThemeBasicBundle/Resources/config/theme/creative.yml' }

sonata_admin:
  dashboard:
      blocks:
          - { position: right, type: presta_cms.block.dashboard.cms }

presta_cms_core:
    websites:
        prestacms-sandbox:
            path: /website/sandbox
            hosts:
                dev:
                    en:
                        locale: en
                        host: sandbox.prestacms.com.local
                    fr:
                        locale: fr
                        host: sandbox.prestacms.fr.local
                prod:
                    en:
                        locale: en
                        host: sandbox.prestacms.com
                    fr:
                        locale: fr
                        host:  sandbox.prestacms.fr
