#app/config/routing.yml
PrestaSitemapBundle:
    resource: "@PrestaSitemapBundle/Resources/config/routing.yml"
    prefix:   /

presta_cms_contact:
    resource: "@PrestaCMSContactBundle/Resources/config/routing.xml"
    prefix:   /

sandbox_service:
    resource: "@SandboxServiceBundle/Controller/"
    type:     annotation
    prefix:   /

presta_sonata_admin_extended:
    resource: "@PrestaSonataAdminExtendedBundle/Resources/config/routing.yml"
    prefix:   /

##Sonata Project
#admin:
#    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
#    prefix: /admin/{_locale}
#
#_sonata_admin:
#    resource: .
#    type: sonata_admin
#    prefix: /admin/{_locale}
#
##override sonata routes
#sonata_admin_dashboard:
#    pattern: /admin/{_locale}/
#    defaults: { _controller: SonataAdminBundle:Core:dashboard }

PrestaCMSCoreBundle:
    resource: "@PrestaCMSCoreBundle/Resources/config/routing.xml"
    prefix:   /admin/{_locale}/

prestacms_user:
    resource: "@PrestaCMSUserBundle/Resources/config/routing.xml"
    prefix: /user

#presta_cms_page_redirect:
#    pattern: /redirect
#    defaults: {_controller: PrestaCMSCoreBundle:Page:redirect}


#phpcrodmbrowser:
#    resource: @SonataDoctrinePHPCRAdminBundle/Resources/config/routing/phpcrodmbrowser.xml
#    prefix: /admin/browser
tree:
    resource: "@SonataDoctrinePHPCRAdminBundle/Resources/config/routing/tree.xml"

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

#ajax
paristime:
    pattern: /paristime
    defaults: {_controller: PrestaCMSCoreBundle:Ajax:paristime}
latime:
    pattern: /latime
    defaults: {_controller: PrestaCMSCoreBundle:Ajax:latime}
